packages:
  - "apps/*"
allowBuilds:
  '@swc/core': false
  sharp: false
  '@apollo/protobufjs': false
  '@parcel/watcher': false
  '@prisma/engines': false
  esbuild: false
  prisma: false
  unrs-resolver: false
